name: Deploy Personal Website via GitHub Pages
on:
  push:
    branches:
      - main # 或 master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # <--- 新增的权限配置
      contents: write # 赋予机器人写入仓库内容的权限
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
